// freemkv-i18n — i18n string loader (shared across the freemkv toolchain)
// MIT — freemkv project
//
// There is no README: this comment is the specification.
//
// The libraries under this crate emit NUMERIC ERROR CODES and never English
// text. This crate is the only place a code becomes something a person reads,
// which makes its failure mode unusual: a bug here does not crash, it produces
// a message. A wrong, blank or silently-English message turns a real failure
// into something that reads as benign, and nothing downstream can tell.
//
// English is compiled into the binary (always available).
// Other languages are compiled in too, and additional ones can be loaded from
// disk at runtime — drop a JSON file next to the binary, done.
//
// Language priority:
//   1. --language flag (set via set_language() before init())
//   2. GNU `LANGUAGE` — a colon-separated priority LIST (`LANGUAGE=de:en`),
//      each entry tried in turn until one has a catalog. It sits above the
//      POSIX vars but is consulted ONLY when the POSIX selection names a real
//      locale: with `LC_ALL=C` (or nothing set) it is ignored, so a script
//      asking for parseable output still gets English.
//   3. LC_ALL / LC_MESSAGES / LANG env var (POSIX precedence: the FIRST of
//      those that is set and non-empty wins outright, even when its value is
//      `C` or `POSIX` — both of which mean English. `LC_ALL=C` is how a script
//      asks for parseable output and it must not be overridden by LC_MESSAGES.)
//   4. English fallback
//
// Catalog resolution walks every prefix of the requested tag, longest first, so
// a three-subtag tag still finds a two-subtag catalog:
//
//   zh-Hans-CN → zh-hans-cn → zh-hans → zh → en
//   pt-BR      → pt-br      → pt      → en
//
// Search paths for on-disk locale files (each tried under the internal
// lowercase name, the underscore form, and BCP-47 canonical case, so an
// operator's `pt-BR.json` is found on a case-sensitive filesystem):
//   1. <binary dir>/locales/xx.json (next to the binary)
//   2. ./locales/xx.json (working directory)
//   3. <home>/.config/freemkv/locales/xx.json
//      (home is $HOME, or %USERPROFILE% on Windows)
//   4. /usr/share/freemkv/locales/xx.json
//      (%PROGRAMDATA%\freemkv\locales on Windows)
//
// To add a language: create locales/xx.json (copy en.json structure) and
// place it in any search path. No code changes needed.
//
// API note — two functions look interchangeable and are not:
//   * `set_language` is the one-shot `--language` override. It must be called
//     BEFORE anything reads a string, and only takes effect once.
//   * `set_locale` is the live switch a GUI uses. It works at any time and can
//     be called repeatedly.
// `get` and `fmt` are deliberately terse crate-root names: every consumer
// re-exports this crate under a module (freemkv does `pub use freemkv_i18n::*;`
// from `strings.rs`), so they are read as `strings::get` / `strings::fmt` at
// the call site. Renaming them would break those consumers for no gain.

use serde_json::Value;
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Mutex, OnceLock, RwLock, RwLockReadGuard, RwLockWriteGuard};

mod locale_code;
use locale_code::{fallback_chain, locale_filenames, normalize_code};

// The catalog the error-code registry test compares against. Checked in and
// regenerated by ci/sync-error-codes.sh — see the module comment for why this
// crate cannot simply depend on libfreemkv.
#[cfg(test)]
mod error_codes;

// The active catalog. An `RwLock` (not `OnceLock`) so a running GUI can switch
// language live via `set_locale`; the CLI still sets it exactly once at
// startup. Reads (`get`/`fmt`) take the read lock; a language switch takes the
// write lock briefly. `None` until first use, then lazily initialized.
static STRINGS: RwLock<Option<Value>> = RwLock::new(None);
static LANG_OVERRIDE: OnceLock<String> = OnceLock::new();
// Whether the catalog currently in `STRINGS` IS the English one. Kept beside it
// (written under the same write lock) purely so a miss can skip the per-key
// English fallback: when English is already active, that fallback is a second
// walk of the identical tree that cannot find anything the first walk did not.
static ACTIVE_IS_EN: AtomicBool = AtomicBool::new(false);

// Serializes the catalog-INSTALLING paths — lazy first-use `get`, `init`,
// `set_locale` — with each other and with `set_language`. It is deliberately
// NOT on the `get`/`fmt` fast path (a catalog already installed): a reader then
// takes only the `STRINGS` read lock and never touches this. It exists to close
// two windows the `STRINGS` lock alone cannot, because resolution reads the
// environment / `--language` override OUTSIDE the `STRINGS` write lock:
//   * a `set_language` override arriving WHILE another thread is mid-resolve —
//     that thread would install an environment-derived catalog and the override
//     would be silently dropped even though `set_language` reported success;
//   * two `set_locale` calls whose resolves complete in the opposite order from
//     which they were called, so the last WRITER wins rather than the last
//     CALLER. Holding this lock across resolve-then-install makes the last
//     caller to acquire it the last to install.
static INIT_LOCK: Mutex<()> = Mutex::new(());

fn init_lock() -> std::sync::MutexGuard<'static, ()> {
    INIT_LOCK.lock().unwrap_or_else(|e| e.into_inner())
}

// ── Shipped languages (auto-generated from locales/*.json by build.rs) ─────
include!(concat!(env!("OUT_DIR"), "/locales_generated.rs"));

// ── Lock access ────────────────────────────────────────────────────────────
//
// A poisoned `RwLock` must not take the process down. `.unwrap()` on a lock
// turns one panic anywhere in the program into a panic in EVERY later call to
// `get`, including the panic handler's own attempt to render a message — the
// user then loses the real error and sees a lock-poisoning backtrace instead.
// The data behind this lock is a parsed JSON catalog: a panic cannot leave it
// half-written into an inconsistent state, so recovering the guard is safe and
// is strictly better than aborting the run over a message lookup.

fn read_strings() -> RwLockReadGuard<'static, Option<Value>> {
    STRINGS.read().unwrap_or_else(|e| e.into_inner())
}

fn write_strings() -> RwLockWriteGuard<'static, Option<Value>> {
    STRINGS.write().unwrap_or_else(|e| e.into_inner())
}

/// Set language override from --language flag. Call before init().
///
/// This is the one-shot pre-init override; use [`set_locale`] to change
/// language while the program is running.
///
/// Once `init()`/`get()` has locked in the active locale (`STRINGS`), this
/// override is dead: the language is already chosen. A call at that point is a
/// caller-ordering bug, so make it visible instead of silently no-opping.
pub fn set_language(lang: &str) {
    // Take INIT_LOCK for the whole check-then-set. Every catalog-installing path
    // (lazy `get`, `init`, `set_locale`) holds it across resolve-then-install,
    // so this cannot interleave with an in-flight resolve: either the override
    // is set BEFORE any resolve begins, or a catalog is already installed and
    // the override is genuinely too late. A brief read guard alone did NOT close
    // this — a `get()` that had already resolved from the environment (outside
    // the lock) but not yet installed would still ignore the override, so the
    // user passed `--language de`, got their system locale, and nothing warned.
    let _init = init_lock();
    let guard = read_strings();
    if guard.is_some() {
        debug_assert!(
            false,
            "set_language(\"{lang}\") called after strings were initialized; use set_locale to switch live"
        );
        eprintln!("warning: --language ignored (set after locale was initialized)");
        return;
    }
    if LANG_OVERRIDE.set(lang.to_string()).is_err()
        && let Some(msg) = language_override_conflict(lang, LANG_OVERRIDE.get().map(String::as_str))
    {
        // A second `--language` used to vanish into `let _ = ...set(..)`. The
        // first one wins, which is a defensible rule, but the user asked for
        // something they did not get and nothing said so.
        eprintln!("{msg}");
    }
}

/// The warning for a `--language` override that arrived after one was already
/// locked in, or `None` when there is nothing worth saying (the same language
/// requested twice changes nothing).
fn language_override_conflict(requested: &str, existing: Option<&str>) -> Option<String> {
    let existing = existing?;
    (existing != requested).then(|| {
        format!(
            "warning: --language {requested} ignored; the language was already set to {existing}"
        )
    })
}

/// Switch the active locale at runtime — the live path a GUI language change
/// uses. Unlike [`set_language`] (a one-shot pre-init override), this
/// re-resolves and swaps the catalog in place, so subsequent `get`/`fmt` calls
/// return the new language without a restart. `code` is any locale string
/// (`"de"`, `"pt-BR"`, `"auto"`); it is normalized and resolved the same way as
/// startup (full tag → language+script → base language → English). Safe to call
/// repeatedly.
pub fn set_locale(code: &str) {
    // Hold INIT_LOCK across resolve-then-install so the LAST CALLER wins. Two
    // concurrent `set_locale`s used to resolve outside any shared lock and race
    // to the write lock, so whichever resolve happened to FINISH last installed
    // last — last-writer-wins, not last-caller-wins, and a GUI that fired a `de`
    // switch after an `fr` one could settle on French. With INIT_LOCK the caller
    // that acquires it later also resolves and installs later.
    //
    // Resolution still runs off the `STRINGS` write lock: it stats up to four
    // directories and may read and parse a file off disk, and every `get` in the
    // process would block on that if it happened under the writer. INIT_LOCK is a
    // separate mutex the read fast path never touches, so serializing switches
    // here does not stall readers.
    let _init = init_lock();
    let (resolved, is_english) = resolve_catalog_tagged(&normalize_code(code));
    let mut w = write_strings();
    ACTIVE_IS_EN.store(is_english, Ordering::Relaxed);
    *w = Some(resolved);
}

/// Initialize strings for the current locale (CLI startup). Idempotent-ish: it
/// (re)resolves from the environment / `--language` override and installs the
/// catalog. `get`/`fmt` also initialize lazily, so calling this is optional.
pub fn init() {
    // Serialize with the other installing paths (see INIT_LOCK) so a concurrent
    // `set_language` cannot land between this resolve and its install.
    let _init = init_lock();
    let (json, is_english) = resolve_catalog_for_candidates(&detect_languages());
    let mut w = write_strings();
    ACTIVE_IS_EN.store(is_english, Ordering::Relaxed);
    *w = Some(json);
}

/// Resolve a SINGLE locale code to a catalog, walking every prefix of the tag
/// from most to least specific and falling back to English (see
/// [`fallback_chain`]), plus whether the catalog it returned is the English one.
/// That flag is what lets `get` skip the per-key English fallback when English
/// is already active. Used by `set_locale` (one explicit code) and the tests.
fn resolve_catalog_tagged(code: &str) -> (Value, bool) {
    resolve_catalog_for_candidates(std::slice::from_ref(&code.to_string()))
}

/// Resolve an ORDERED list of candidate locale codes — a GNU `LANGUAGE`
/// priority list, or a single code — to a catalog. Each candidate's whole
/// prefix chain is tried in turn; English is the fallback only after EVERY
/// candidate has failed. This is what makes `LANGUAGE=sw:de` reach German when
/// Swahili does not ship, instead of stopping at the first miss and rendering
/// English.
fn resolve_catalog_for_candidates(candidates: &[String]) -> (Value, bool) {
    for candidate in candidates {
        for step in fallback_chain(candidate) {
            if let Some(v) = load_for(&step) {
                return (v, step == "en");
            }
        }
    }
    // Notify the user when they explicitly requested a locale that isn't
    // available (VAL-3). Plain English is intentional here. The first candidate
    // is the one the user most wanted, so it is the one worth naming.
    match candidates.first() {
        Some(first) if first != "en" => {
            eprintln!("freemkv: locale '{first}' not found, using English");
        }
        _ => {}
    }
    (english_catalog().clone(), true)
}

/// Load one locale code: compiled-in first, then disk search paths. `None` if
/// that exact code has no catalog anywhere (the caller then tries the next,
/// less specific code in the fallback chain, then English).
fn load_for(code: &str) -> Option<Value> {
    if let Some(data) = bundled_locale(code) {
        // A bundled catalog is validated at build time (build.rs `include_str!`s
        // it) and re-parsed by the test suite, so a parse failure here is
        // unreachable in a correctly built binary. `expect` still made it a
        // landmine: it would abort the process in the one crate whose entire job
        // is to render a message when something ELSE fails. Log and fall through
        // to the disk search / next fallback candidate instead — the same
        // degradation an absent catalog gets — so no data glitch can turn a
        // string lookup into a crash.
        return match serde_json::from_str(data) {
            Ok(v) => Some(v),
            Err(e) => {
                eprintln!("freemkv: bundled locale '{code}' failed to parse ({e}); ignoring it");
                None
            }
        };
    }
    load_locale_file(code)
}

/// Get a string by dotted path (e.g. "disc.scanning", "error.no_drive").
///
/// A key present in the active locale renders its value. A key present in
/// English but missing (or blank) in the active locale falls back to the
/// English string, reported once (see [`lookup_or_english`]). Only a key that
/// exists in NO catalog renders as the dotted path itself, which keeps a truly
/// missing translation visible rather than blank.
pub fn get(path: &str) -> String {
    // Fast path: catalog already loaded — take the read lock and look up.
    {
        let guard = read_strings();
        if let Some(v) = guard.as_ref() {
            return lookup_or_english(v, path, ACTIVE_IS_EN.load(Ordering::Relaxed));
        }
    }
    // First use with no explicit init(): resolve from the environment /
    // --language override (honoring any pre-init set_language) and install it.
    // INIT_LOCK serializes this whole resolve-then-install with `set_language`,
    // `init` and `set_locale`, so a `--language` override cannot be resolved
    // AROUND (set after we read the environment but before we install), and a
    // concurrent `set_locale` cannot interleave its own resolve with ours.
    let _init = init_lock();
    // Another thread may have installed a catalog while we waited for INIT_LOCK;
    // if so, use it rather than resolving and installing a second time.
    {
        let guard = read_strings();
        if let Some(v) = guard.as_ref() {
            return lookup_or_english(v, path, ACTIVE_IS_EN.load(Ordering::Relaxed));
        }
    }
    let (json, is_english) = resolve_catalog_for_candidates(&detect_languages());
    let mut w = write_strings();
    ACTIVE_IS_EN.store(is_english, Ordering::Relaxed);
    *w = Some(json);
    let active = w.as_ref().unwrap_or_else(|| english_catalog());
    lookup_or_english(active, path, ACTIVE_IS_EN.load(Ordering::Relaxed))
}

/// Get a string and replace {key} placeholders with values.
///
/// Substitution is a SINGLE pass over the catalog string: a value that itself
/// contains `{something}` is copied out verbatim and never rescanned. The old
/// implementation ran `String::replace` once per argument over the ACCUMULATING
/// result, so a disc label containing the literal text `{size}` was rewritten
/// by the next argument's pass — disc-derived text was being interpreted as
/// format syntax.
///
/// A `{` that does not open a well-formed `{name}` is a literal `{`, and a
/// `{name}` with no matching argument is left in place (visible, so a caller
/// that forgot an argument is caught). There is deliberately no `{{` escape:
/// the catalogs are translator-authored JSON, no catalog uses one, and
/// inventing an escape would silently rewrite any translation that ever
/// contains a doubled brace.
pub fn fmt(path: &str, args: &[(&str, &str)]) -> String {
    substitute(&get(path), |name| {
        args.iter().find(|(k, _)| *k == name).map(|(_, v)| *v)
    })
}

/// The one and only placeholder scanner. `resolve` is called with each
/// placeholder name; `None` leaves the placeholder untouched.
///
/// Tests use this too, rather than a second hand-written scanner, so the check
/// that placeholders agree across locales cannot drift from what `fmt`
/// actually substitutes.
fn substitute<'a>(s: &str, mut resolve: impl FnMut(&str) -> Option<&'a str>) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(open) = rest.find('{') {
        out.push_str(&rest[..open]);
        let after = &rest[open + 1..];
        match after.find('}') {
            // A real placeholder is a balanced `{...}` with no nested brace.
            Some(close) if !after[..close].contains('{') => {
                let name = &after[..close];
                match resolve(name) {
                    Some(value) => out.push_str(value),
                    None => {
                        out.push('{');
                        out.push_str(name);
                        out.push('}');
                    }
                }
                rest = &after[close + 1..];
            }
            _ => {
                out.push('{');
                rest = after;
            }
        }
    }
    out.push_str(rest);
    out
}

/// Look up the localized message for a libfreemkv error code, WITHOUT any
/// argument.
///
/// Error strings live under the dotted path `error.E<code>` (e.g. code `7022`
/// → key `error.E7022`), matching how `libfreemkv::Error::code()` values are
/// keyed in the locale files. The crate stays free of any `libfreemkv`
/// dependency by taking the bare numeric code rather than the `Error` type.
///
/// Twenty-three of the codes have an English string that embeds a placeholder
/// — `{detail}` (a device path, a sector, an HTTP status), `{hash}` (E7022's
/// disc id) or `{path}` (E9067/E9068's file name) — that only a caller holding
/// the originating error can fill. This entry point has none of those values,
/// so a raw lookup would render the literal characters `{detail}`/`{hash}`/
/// `{path}` to the user: exactly the "reads as benign / actually broken"
/// failure this crate exists to prevent, and the one a bare-code caller such as
/// autorip's `error_message(err.code())` hit. It therefore DROPS every unfilled
/// placeholder (and tidies what that leaves), rendering a complete, brace-free
/// message. The specific value is lost; a caller that HAS the detail must use
/// [`error_message_with`] so it is preserved.
///
/// Falls back to the key path (`error.E<code>`) if the code has no string —
/// same miss behavior as [`get`]. The
/// `libfreemkv_error_codes_all_have_english_strings` test is what stops that
/// from being the shipped state of a new code.
pub fn error_message(code: u32) -> String {
    render_error_message(code, None)
}

/// Look up the localized message for a libfreemkv error code and substitute the
/// `{detail}` placeholder with `detail`.
///
/// This is the detail-preserving companion to [`error_message`]. The error
/// strings that embed `{detail}` (a device path, a failing sector, an HTTP
/// status, a URL …) render their full, specific text through this entry point;
/// a caller that holds the originating `libfreemkv::Error` — which carries that
/// detail — should call this so the value reaches the user. A string with no
/// `{detail}` ignores the argument. Any OTHER unfilled placeholder (`{hash}`,
/// `{path}`) is dropped, exactly as in [`error_message`], so nothing leaks.
pub fn error_message_with(code: u32, detail: &str) -> String {
    render_error_message(code, Some(detail))
}

/// Render `error.E<code>`, substituting `{detail}` when `detail` is `Some` and
/// DROPPING every other (or every, when `detail` is `None`) placeholder, then
/// tidying the punctuation the drop leaves behind. A single substitution pass
/// does the fill-or-drop, so a `detail` value that itself contains `{…}` is
/// copied out verbatim and never rescanned.
fn render_error_message(code: u32, detail: Option<&str>) -> String {
    let raw = get(&format!("error.E{code}"));
    if !raw.contains('{') {
        // The common case (no placeholder, or the key-path miss) — nothing to
        // fill, drop or tidy.
        return raw;
    }
    let filled = substitute(&raw, |name| match (name, detail) {
        ("detail", Some(d)) => Some(d),
        // Every unfilled placeholder is removed rather than left to reach the
        // user as literal `{name}` text.
        _ => Some(""),
    });
    tidy_empty_slots(&filled)
}

/// Collapse the artifacts a dropped placeholder leaves behind so the message is
/// clean and brace-free in every locale: an empty bracket or quote (`()`, `''`,
/// and their full-width `（）` forms, which the CJK catalogs use), a label-only
/// parenthetical like `(id:)` left when E7022's `{hash}` value goes, a space
/// before `.,:;!?)`/`）`, a space after `(`/`（`, a dangling trailing `:`, and
/// runs of spaces. Language-neutral — it only moves whitespace, brackets, quotes
/// and punctuation, never letters — so it cannot corrupt a translation, and it
/// covers the non-ASCII catalogs the unit tests could otherwise miss.
fn tidy_empty_slots(s: &str) -> String {
    // A parenthetical whose value was a placeholder now reads as a bare label
    // and a colon (`(id:)`, `（id：）`) — drop the whole group. Done first, while
    // the content is still recognizable, before the space rules reshuffle it.
    let mut out = drop_colon_only_parentheticals(s);
    // Drop an empty bracket or quote the removed value left, ASCII and
    // full-width, with an ASCII or ideographic space inside (`(HTTP )` /
    // `（HTTP　）` are reduced to `(HTTP)` / `（HTTP）` by the space-before-close
    // rules below; `'{path}'` collapses to `''`).
    for empty in ["( )", "()", "（）", "（ ）", "（\u{3000}）", "''", "\"\""] {
        out = out.replace(empty, "");
    }
    // Remove a space (ASCII or ideographic) that now sits before closing
    // punctuation, or after an opening bracket.
    for (from, to) in [
        (" .", "."),
        (" ,", ","),
        (" :", ":"),
        (" ;", ";"),
        (" !", "!"),
        (" ?", "?"),
        (" )", ")"),
        ("( ", "("),
        (":.", "."),
        (" ）", "）"),
        ("\u{3000}）", "）"),
        ("（ ", "（"),
        ("（\u{3000}", "（"),
    ] {
        while out.contains(from) {
            out = out.replace(from, to);
        }
    }
    // Collapse doubled spaces, then trim, then drop a now-dangling trailing
    // colon (`Drive reset failed:` → `Drive reset failed`).
    while out.contains("  ") {
        out = out.replace("  ", " ");
    }
    let trimmed = out.trim();
    trimmed.strip_suffix(':').unwrap_or(trimmed).to_string()
}

/// Remove every parenthetical — ASCII `( )` or full-width `（ ）` — whose visible
/// content is a bare label ending in a colon (`(id:)`, `（id：）`). That shape is
/// only ever produced by dropping a placeholder that WAS the parenthetical's
/// value (E7022's `(id: {hash})` → `(id:)`); a real parenthetical carries a
/// value after its colon, so this never touches legitimate text. Scans the
/// innermost-plausible group (no nested opener in the content) and restarts
/// after each removal.
fn drop_colon_only_parentheticals(s: &str) -> String {
    let mut out = s.to_string();
    for (open, close) in [("(", ")"), ("（", "）")] {
        let mut search = 0;
        while let Some(rel_open) = out[search..].find(open) {
            let o = search + rel_open;
            let after = o + open.len();
            if let Some(rel_close) = out[after..].find(close) {
                let c = after + rel_close;
                let content = out[after..c].trim();
                if !content.is_empty()
                    && !content.contains(open)
                    && (content.ends_with(':') || content.ends_with('：'))
                {
                    out.replace_range(o..c + close.len(), "");
                    search = 0;
                    continue;
                }
            }
            search = o + open.len();
        }
    }
    out
}

/// Returns the bundled (compiled-in) locale JSON for `code`, if that language
/// is shipped with the crate. Exposed so downstream contract tests can validate
/// locale coverage against the exact bundled data without re-bundling the
/// files themselves (and without relying on a sibling-directory path that only
/// exists in a local checkout).
pub fn bundled_locale_json(code: &str) -> Option<&'static str> {
    bundled_locale(code)
}

// ── Internal ───────────────────────────────────────────────────────────────

/// The parsed English catalog, parsed ONCE for the life of the process.
///
/// The per-key English fallback used to call `serde_json::from_str(LOCALE_EN)`
/// on every miss — a full parse of a 45 KB, 580-key document, thrown away
/// immediately, per lookup. A locale with a handful of untranslated keys paid
/// that on every screen refresh.
fn english_catalog() -> &'static Value {
    static EN: OnceLock<Value> = OnceLock::new();
    EN.get_or_init(|| serde_json::from_str(LOCALE_EN).expect("invalid en.json"))
}

/// The ordered list of catalog codes to try for the current environment, most
/// preferred first — a GNU `LANGUAGE` priority list, or the single POSIX
/// selection. `set_language`'s one-shot override, when present, is the whole
/// list.
fn detect_languages() -> Vec<String> {
    if let Some(lang) = LANG_OVERRIDE.get() {
        return vec![normalize_code(lang)];
    }
    locale_candidates_from_env(|var| std::env::var(var).ok())
}

/// POSIX precedence: `LC_ALL` overrides every other locale variable, then the
/// category-specific `LC_MESSAGES`, then `LANG` as the fallback default. The
/// FIRST of those that is set and non-empty wins outright.
///
/// It used to skip a variable whose value was `C` or `POSIX`, which made an
/// explicitly-set `LC_ALL=C` behave as if it were unset and let `LC_MESSAGES`
/// take over: `LC_ALL=C LC_MESSAGES=de_DE.UTF-8 freemkv …` printed German. That
/// is backwards — `LC_ALL=C` is the standard way to demand the unlocalized,
/// parseable output a script is about to grep, and the code's own comment said
/// LC_ALL overrides everything. Nothing special is needed to honor it now:
/// `normalize_code` maps `C` and `POSIX` to English on its own, because neither
/// is a two- or three-letter language subtag.
fn locale_from_env(get_var: impl Fn(&str) -> Option<String>) -> String {
    ["LC_ALL", "LC_MESSAGES", "LANG"]
        .iter()
        .find_map(|var| get_var(var).filter(|v| !v.is_empty()))
        .unwrap_or_else(|| "en".to_string())
}

/// The ordered candidate codes for the environment, applying GNU `LANGUAGE`
/// precedence on top of the POSIX selection.
///
/// GNU `LANGUAGE` sits ABOVE the POSIX vars, but only for message translation
/// and only when the selected locale is a real one. It is a colon-separated
/// priority LIST (`LANGUAGE=de:en` means "German, then English"): every entry
/// is a candidate, tried in order by the resolver until one has a catalog — so
/// `LANGUAGE=sw:de` reaches German even though Swahili does not ship, rather
/// than stopping at the first miss. It is IGNORED when the POSIX selection is
/// the `C` / `POSIX` locale (or nothing is set at all) — that is how `LC_ALL=C`
/// keeps demanding parseable output even with `LANGUAGE` exported. Without any
/// of this, `LANGUAGE=de:en LANG=en_US.UTF-8` (the shape a German user's
/// desktop sets) rendered English, because `LANGUAGE` was never consulted.
fn locale_candidates_from_env(get_var: impl Fn(&str) -> Option<String>) -> Vec<String> {
    let selected = ["LC_ALL", "LC_MESSAGES", "LANG"]
        .iter()
        .find_map(|var| get_var(var).filter(|v| !v.is_empty()));

    if !is_posix_c_locale(selected.as_deref().unwrap_or("C"))
        && let Some(language) = get_var("LANGUAGE").filter(|v| !v.is_empty())
    {
        let candidates: Vec<String> = language
            .split(':')
            .filter(|entry| !entry.is_empty())
            .map(normalize_code)
            .collect();
        if !candidates.is_empty() {
            return candidates;
        }
    }

    vec![normalize_code(&locale_from_env(&get_var))]
}

/// Whether a locale VALUE names the POSIX `C` locale (`C`, `POSIX`, their
/// codeset/modifier-suffixed forms, or empty). Used to decide when GNU
/// `LANGUAGE` must be ignored. This is a check on the raw locale NAME, not on
/// `normalize_code`'s output, because `en_US` also normalizes to English yet is
/// a real locale over which `LANGUAGE` still takes precedence.
fn is_posix_c_locale(val: &str) -> bool {
    let base = val.trim().split(['.', '@']).next().unwrap_or("");
    base.is_empty() || base.eq_ignore_ascii_case("C") || base.eq_ignore_ascii_case("POSIX")
}

/// The user's home directory, by whichever variable this platform sets.
///
/// `$HOME` alone gated search path 3, and stock Windows does not set it — the
/// documented per-user locale directory simply did not exist there, on a crate
/// whose header comment promises the same four search paths everywhere.
fn home_dir() -> Option<PathBuf> {
    #[cfg(windows)]
    const HOME_VARS: &[&str] = &["USERPROFILE", "HOME"];
    #[cfg(not(windows))]
    const HOME_VARS: &[&str] = &["HOME"];

    HOME_VARS
        .iter()
        .filter_map(std::env::var_os)
        .find(|v| !v.is_empty())
        .map(PathBuf::from)
}

/// The machine-wide locale directory. `/usr/share` has no meaning on Windows,
/// where the equivalent is `%PROGRAMDATA%`.
fn system_locale_dir() -> Option<PathBuf> {
    #[cfg(windows)]
    {
        std::env::var_os("PROGRAMDATA")
            .filter(|v| !v.is_empty())
            .map(|p| PathBuf::from(p).join("freemkv").join("locales"))
    }
    #[cfg(not(windows))]
    {
        Some(PathBuf::from("/usr/share/freemkv/locales"))
    }
}

/// The directories searched for on-disk catalogs, in priority order. Split out
/// from the environment lookups so the ordering and the platform differences
/// can be tested without mutating process-wide state.
fn locale_search_dirs_from(
    exe_dir: Option<PathBuf>,
    home: Option<PathBuf>,
    system: Option<PathBuf>,
) -> Vec<PathBuf> {
    let mut dirs = Vec::with_capacity(4);
    if let Some(dir) = exe_dir {
        dirs.push(dir.join("locales"));
    }
    dirs.push(PathBuf::from("locales"));
    if let Some(home) = home {
        dirs.push(home.join(".config").join("freemkv").join("locales"));
    }
    if let Some(system) = system {
        dirs.push(system);
    }
    dirs
}

fn locale_search_dirs() -> Vec<PathBuf> {
    let exe_dir = std::env::current_exe()
        .ok()
        .and_then(|exe| exe.parent().map(Path::to_path_buf));
    locale_search_dirs_from(exe_dir, home_dir(), system_locale_dir())
}

/// Try to load a catalog for `code` from the search paths.
fn load_locale_file(code: &str) -> Option<Value> {
    let names = locale_filenames(code);
    for dir in locale_search_dirs() {
        for name in &names {
            if let Some(v) = try_load(&dir.join(name)) {
                return Some(v);
            }
        }
    }
    None
}

/// The diagnostic for a locale file that could not be read, or `None` when the
/// error means "there is no such file", which is the normal case for three of
/// the four search paths.
///
/// The read used to be `.ok()?`, which collapsed those two into one: a file
/// that exists but cannot be read — wrong permissions, a directory where a file
/// was expected, a broken symlink target, non-UTF-8 bytes — was indistinguishable
/// from a file that was never there, and the user was then told the locale was
/// "not found" while looking straight at it. The very next branch already
/// reports an unparseable file; this makes the two symmetrical.
fn locale_read_diagnostic(path: &Path, error: &std::io::Error) -> Option<String> {
    (error.kind() != std::io::ErrorKind::NotFound).then(|| {
        format!(
            "freemkv: cannot read locale file {}: {}",
            path.display(),
            error
        )
    })
}

fn try_load(path: &Path) -> Option<Value> {
    let data = match std::fs::read_to_string(path) {
        Ok(data) => data,
        Err(e) => {
            if let Some(msg) = locale_read_diagnostic(path, &e) {
                eprintln!("{msg}");
            }
            return None;
        }
    };
    // A missing file is fine (the loader tries the next search path), but a
    // file that exists yet fails to parse is almost certainly an operator
    // mistake — surface it instead of silently falling back to English.
    match serde_json::from_str(&data) {
        Ok(v) => Some(v),
        Err(e) => {
            eprintln!(
                "freemkv: ignoring invalid locale file {}: {}",
                path.display(),
                e
            );
            None
        }
    }
}

/// Report a key that had to be served from English, once per key.
///
/// Returns whether it actually emitted, which is also how the rate limiting is
/// tested. The substitution itself was completely silent: a locale missing a
/// translation produced a perfectly ordinary-looking English sentence in the
/// middle of a German UI and nothing, anywhere, recorded that a translation was
/// missing — the exact shape this project treats as a defect in its own right,
/// a fallback that hides what it is covering for. Per-key deduplication keeps a
/// progress loop from flooding the terminal without hiding the size of the gap:
/// the number of lines IS the number of untranslated keys in use.
fn report_missing_translation(path: &str) -> bool {
    static REPORTED: OnceLock<Mutex<BTreeSet<String>>> = OnceLock::new();
    let mut seen = REPORTED
        .get_or_init(|| Mutex::new(BTreeSet::new()))
        .lock()
        .unwrap_or_else(|e| e.into_inner());
    if seen.insert(path.to_string()) {
        eprintln!("freemkv: no translation for '{path}' in the active locale, using English");
        return true;
    }
    false
}

/// Look up `path`, falling back to the English string for that key.
///
/// The catalog-level fallback in [`resolve_catalog_tagged`] only chooses WHICH
/// file to load; without this per-key one, a key present in en.json but missing
/// from the active locale rendered as the raw path — a user running under `de`
/// saw the literal text `error.E9053`.
///
/// That is strictly worse than English: it is not a message in any language,
/// and it leaks an internal key into the UI. A translation gap should degrade
/// to a language the user may not read, not to something nobody can.
///
/// A BLANK value counts as a miss, not a hit. An override file whose key maps to
/// `""` (or only whitespace) used to be a "successful" lookup that rendered as
/// an empty message — which reads as success while saying nothing — with no
/// diagnostic. It is now treated exactly like an absent key: report it and fall
/// back to English (or to the path if English lacks it too).
///
/// `active_is_english` short-circuits the second walk when the catalog in hand
/// IS the English one, where it can only miss again.
fn lookup_or_english(strings: &Value, path: &str, active_is_english: bool) -> String {
    if let Some(s) = lookup_in(strings, path)
        && !s.trim().is_empty()
    {
        return s;
    }
    if !active_is_english
        && let Some(s) = lookup_in(english_catalog(), path)
        && !s.trim().is_empty()
    {
        report_missing_translation(path);
        return s;
    }
    path.to_string()
}

/// One catalog, no fallback. Returns `None` for a missing or non-string node so
/// the caller can decide what to do about it.
fn lookup_in(strings: &Value, path: &str) -> Option<String> {
    let mut node = strings;
    for part in path.split('.') {
        node = node.get(part)?;
    }
    node.as_str().map(|s| s.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::cell::RefCell;

    /// Extract `{word}` placeholders from a format string.
    ///
    /// This drives the PRODUCTION scanner rather than reimplementing it. The
    /// test helper used to be a second, independently written parser that
    /// treated `{{` as an escape — something `fmt` has never done — so the
    /// parity check was asserting against a placeholder grammar the runtime
    /// does not speak. A locale using a construct the helper skipped and `fmt`
    /// substituted (or the reverse) would have passed the suite and rendered
    /// wrong. There is one grammar now, by construction.
    fn placeholders(s: &str) -> Vec<String> {
        let found = RefCell::new(Vec::new());
        substitute(s, |name| {
            found.borrow_mut().push(format!("{{{name}}}"));
            None
        });
        found.into_inner()
    }

    /// Collect all dotted key paths from a JSON value (e.g. "disc.scanning", "error.E1000").
    fn collect_keys(value: &Value, prefix: &str, out: &mut Vec<String>) {
        if let Some(obj) = value.as_object() {
            for (k, v) in obj {
                let path = if prefix.is_empty() {
                    k.clone()
                } else {
                    format!("{}.{}", prefix, k)
                };
                if v.is_object() {
                    collect_keys(v, &path, out);
                } else {
                    out.push(path);
                }
            }
        }
    }

    fn verify_locale(code: &str, data: &str) {
        let locale: Value = serde_json::from_str(data)
            .unwrap_or_else(|e| panic!("{}.json: invalid JSON: {}", code, e));

        let en = english_catalog();
        let mut en_keys = Vec::new();
        collect_keys(en, "", &mut en_keys);

        let mut locale_keys = Vec::new();
        collect_keys(&locale, "", &mut locale_keys);

        // Every English key must exist in the locale
        let mut missing = Vec::new();
        for key in &en_keys {
            if !locale_keys.contains(key) {
                missing.push(key.clone());
            }
        }
        assert!(
            missing.is_empty(),
            "{}.json missing {} keys: {:?}",
            code,
            missing.len(),
            missing
        );

        // ...and no key may exist in the locale that English does not have.
        // Parity was one-directional, so retiring a string from en.json left it
        // behind in all 29 locales with nothing to flag it: a stale entry that
        // translators keep re-translating and reviewers keep reading as live.
        // Both directions now, so a removal has to be completed everywhere.
        let mut extra = Vec::new();
        for key in &locale_keys {
            if !en_keys.contains(key) {
                extra.push(key.clone());
            }
        }
        assert!(
            extra.is_empty(),
            "{}.json has {} key(s) not present in en.json: {:?}",
            code,
            extra.len(),
            extra
        );

        // Placeholders must match EXACTLY, in both directions, against the RAW
        // catalogs.
        //
        // Two holes used to sit here. The values were read through `lookup`,
        // the production accessor, which carries the per-key English fallback:
        // a locale whose leaf was a number, an object or an empty string
        // returned the ENGLISH text and every assertion below passed on it. The
        // parity test could not fail on the wrong-type/blank-value class it
        // exists to catch. And the comparison ran one way only, so an EXTRA
        // `{code}` invented in a translation — which no caller supplies and
        // which therefore renders to the user as the literal characters
        // `{code}` — was invisible.
        for key in &en_keys {
            let en_val = lookup_in(en, key)
                .unwrap_or_else(|| panic!("en.json key '{key}' is not a non-empty string"));
            let locale_val = lookup_in(&locale, key).unwrap_or_else(|| {
                panic!("{code}.json key '{key}': not a string (number, object, bool or null)")
            });
            assert!(
                !locale_val.trim().is_empty(),
                "{code}.json key '{key}': empty value — renders as a blank message, \
                 which reads as success"
            );

            let mut en_ph = placeholders(&en_val);
            let mut locale_ph = placeholders(&locale_val);
            en_ph.sort();
            en_ph.dedup();
            locale_ph.sort();
            locale_ph.dedup();
            assert_eq!(
                en_ph, locale_ph,
                "{code}.json key '{key}': placeholders differ from en.json \
                 (en: '{en_val}', {code}: '{locale_val}')"
            );
        }
    }

    #[test]
    fn normalize_code_does_not_panic_on_multibyte() {
        // Regression: byte-slicing `s[..2]` panicked on a leading multibyte
        // char (e.g. `--language あ`, `LC_ALL=€a`). Untrusted input must never
        // panic — it must fall back to English (or the ASCII language part).
        // "de" is a real, valid ASCII tag mixed into the same loop so the
        // `code.split('-').all(...)` arm of the assertion actually runs at
        // least once — every other input here folds to "en" and short-circuits
        // past it.
        for input in ["あx", "€a", "Ⓐb", "😀x", "あ", "", ".", "_", "@", "ñ", "de"] {
            let code = normalize_code(input);
            // A malformed leading subtag must fall back to English; a valid one
            // yields a lowercase-ASCII tag (lang plus optional -script/-region).
            assert!(
                code == "en"
                    || code
                        .split('-')
                        .all(|p| !p.is_empty() && p.chars().all(|c| c.is_ascii_alphanumeric())),
                "normalize_code({input:?}) = {code:?}: must be 'en' or a clean ASCII tag"
            );
        }
    }

    #[test]
    fn normalize_code_extracts_language_part() {
        // Region and script are now PRESERVED (lowercase, hyphen-joined).
        assert_eq!(normalize_code("fr_FR.UTF-8"), "fr-fr");
        assert_eq!(normalize_code("de"), "de");
        assert_eq!(normalize_code("PT_BR"), "pt-br");
        assert_eq!(normalize_code("en-US"), "en-us");
        assert_eq!(normalize_code("es.UTF-8@modifier"), "es");
        assert_eq!(normalize_code("es-419"), "es-419");
        assert_eq!(normalize_code("zh_Hant"), "zh-hant");
        // Chinese region → script inference.
        assert_eq!(normalize_code("zh_TW"), "zh-hant");
        assert_eq!(normalize_code("zh_CN"), "zh-hans");
        assert_eq!(normalize_code("zh"), "zh-hans");
        // Non-letters fall back rather than producing a bogus code.
        assert_eq!(normalize_code("12"), "en");
        assert_eq!(normalize_code("x"), "en");
        // The POSIX locales are not language subtags, so they land on English
        // without needing a special case — see `locale_from_env`.
        assert_eq!(normalize_code("C"), "en");
        assert_eq!(normalize_code("C.UTF-8"), "en");
        assert_eq!(normalize_code("POSIX"), "en");
    }

    /// Catches the missing `lang-script` rung: a chain that goes straight from
    /// the full tag to the first subtag skips `zh-hans` entirely.
    #[test]
    fn fallback_chain_walks_every_prefix_longest_first() {
        assert_eq!(
            fallback_chain("zh-hans-cn"),
            ["zh-hans-cn", "zh-hans", "zh"]
        );
        assert_eq!(
            fallback_chain("zh-hant-hk"),
            ["zh-hant-hk", "zh-hant", "zh"]
        );
        assert_eq!(
            fallback_chain("sr-latn-rs"),
            ["sr-latn-rs", "sr-latn", "sr"]
        );
        assert_eq!(fallback_chain("pt-br"), ["pt-br", "pt"]);
        assert_eq!(fallback_chain("es-419"), ["es-419", "es"]);
        assert_eq!(fallback_chain("de"), ["de"]);
    }

    /// The bug a Simplified Chinese user actually felt: macOS hands the process
    /// `zh-Hans-CN`, no `zh.json` ships, and the two-step fallback jumped over
    /// `zh-hans.json` — which IS compiled into the binary — straight to
    /// English. Silent: an English UI, no warning, nothing in any log.
    ///
    /// Mutating the chain back to `full tag → first subtag` fails this.
    #[test]
    fn three_subtag_tags_reach_their_script_catalog() {
        let hans: Value = serde_json::from_str(bundled_locale_json("zh-hans").unwrap()).unwrap();
        let hant: Value = serde_json::from_str(bundled_locale_json("zh-hant").unwrap()).unwrap();

        for tag in ["zh-Hans-CN", "zh_Hans_SG", "zh-Hans"] {
            let got = resolve_catalog_tagged(&normalize_code(tag)).0;
            assert_eq!(got, hans, "{tag} must resolve to the Simplified catalog");
            assert_ne!(
                got,
                *english_catalog(),
                "{tag} silently fell back to English"
            );
        }
        for tag in ["zh-Hant-TW", "zh-Hant-HK", "zh_Hant_MO"] {
            let got = resolve_catalog_tagged(&normalize_code(tag)).0;
            assert_eq!(got, hant, "{tag} must resolve to the Traditional catalog");
        }
        // Region-only tags still land on their base language, and a tag with no
        // catalog anywhere still ends at English.
        let pt: Value = serde_json::from_str(bundled_locale_json("pt").unwrap()).unwrap();
        assert_eq!(resolve_catalog_tagged(&normalize_code("pt-PT")).0, pt);
        assert_eq!(
            resolve_catalog_tagged(&normalize_code("xx-YY")).0,
            *english_catalog()
        );
    }

    /// Catches `LC_ALL=C` being treated as unset. POSIX makes LC_ALL an
    /// override: with it set, LC_MESSAGES and LANG are not consulted at all.
    #[test]
    fn lc_all_overrides_every_other_locale_variable() {
        let env = |pairs: &[(&str, &str)]| {
            let owned: Vec<(String, String)> = pairs
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect();
            move |var: &str| {
                owned
                    .iter()
                    .find(|(k, _)| k == var)
                    .map(|(_, v)| v.to_string())
            }
        };

        // The headline case: an explicit `LC_ALL=C` must win, and `C` means
        // English. It used to fall through and print German.
        assert_eq!(
            normalize_code(&locale_from_env(env(&[
                ("LC_ALL", "C"),
                ("LC_MESSAGES", "de_DE.UTF-8"),
                ("LANG", "fr_FR.UTF-8"),
            ]))),
            "en"
        );
        assert_eq!(
            normalize_code(&locale_from_env(env(&[
                ("LC_ALL", "POSIX"),
                ("LANG", "de_DE.UTF-8"),
            ]))),
            "en"
        );
        // A real LC_ALL still wins over the others.
        assert_eq!(
            locale_from_env(env(&[("LC_ALL", "de_DE.UTF-8"), ("LANG", "fr_FR")])),
            "de_DE.UTF-8"
        );
        // An EMPTY variable is "unset" in POSIX, so the next one is consulted.
        assert_eq!(
            locale_from_env(env(&[("LC_ALL", ""), ("LC_MESSAGES", "it_IT")])),
            "it_IT"
        );
        assert_eq!(
            locale_from_env(env(&[("LC_MESSAGES", ""), ("LANG", "nl_NL")])),
            "nl_NL"
        );
        // Nothing set at all → English.
        assert_eq!(locale_from_env(env(&[])), "en");
    }

    /// Catches the loader building one lowercase filename and reading it
    /// exact-case: an operator's `locales/pt-BR.json` is then invisible on any
    /// case-sensitive filesystem, while `build.rs` happily bundles that same
    /// spelling.
    #[test]
    fn locale_filenames_cover_the_spellings_operators_actually_write() {
        assert_eq!(
            locale_filenames("pt-br"),
            ["pt-br.json", "pt_br.json", "pt-BR.json", "pt_BR.json"]
        );
        assert_eq!(
            locale_filenames("zh-hans-cn"),
            [
                "zh-hans-cn.json",
                "zh_hans_cn.json",
                "zh-Hans-CN.json",
                "zh_Hans_CN.json"
            ]
        );
        // A numeric region has no case to canonicalize.
        assert_eq!(locale_filenames("es-419"), ["es-419.json", "es_419.json"]);
        // A bare language has exactly one spelling — no wasted stat calls.
        assert_eq!(locale_filenames("de"), ["de.json"]);
    }

    /// Catches search path 3 being gated on `$HOME` (unset on stock Windows,
    /// which uses `%USERPROFILE%`) and path 4 being a hardcoded `/usr/share`
    /// that means nothing there. The crate's header promises the same four
    /// paths on all three platforms.
    #[test]
    fn search_dirs_are_ordered_and_survive_a_missing_home() {
        let dirs = locale_search_dirs_from(
            Some(PathBuf::from("/opt/freemkv/bin")),
            Some(PathBuf::from("/opt/testhome")),
            Some(PathBuf::from("/usr/share/freemkv/locales")),
        );
        assert_eq!(
            dirs,
            [
                PathBuf::from("/opt/freemkv/bin/locales"),
                PathBuf::from("locales"),
                PathBuf::from("/opt/testhome/.config/freemkv/locales"),
                PathBuf::from("/usr/share/freemkv/locales"),
            ]
        );
        // No home and no system dir must not drop the two that remain.
        assert_eq!(
            locale_search_dirs_from(Some(PathBuf::from("/opt/bin")), None, None),
            [PathBuf::from("/opt/bin/locales"), PathBuf::from("locales")]
        );

        // The live wiring must produce the working directory entry everywhere,
        // and must not offer a POSIX system path on Windows.
        let live = locale_search_dirs();
        assert!(live.contains(&PathBuf::from("locales")));
        #[cfg(windows)]
        assert!(
            !live.iter().any(|d| d.starts_with("/usr")),
            "/usr/share is meaningless on Windows: {live:?}"
        );
        #[cfg(not(windows))]
        assert!(live.contains(&PathBuf::from("/usr/share/freemkv/locales")));
    }

    /// Catches `read_to_string(..).ok()?`, which made an unreadable file look
    /// exactly like an absent one and left the user reading "locale not found"
    /// about a file sitting right there.
    #[test]
    fn an_unreadable_locale_file_is_reported_and_an_absent_one_is_not() {
        use std::io::{Error, ErrorKind};
        let path = Path::new("/tmp/freemkv/locales/sw.json");

        assert!(
            locale_read_diagnostic(path, &Error::from(ErrorKind::NotFound)).is_none(),
            "a file that is simply not there is the normal case for three of \
             the four search paths and must stay silent"
        );
        for kind in [
            ErrorKind::PermissionDenied,
            ErrorKind::IsADirectory,
            ErrorKind::InvalidData,
        ] {
            let msg = locale_read_diagnostic(path, &Error::from(kind))
                .unwrap_or_else(|| panic!("{kind:?} must be reported, not swallowed"));
            assert!(
                msg.contains("sw.json"),
                "diagnostic must name the file: {msg}"
            );
        }

        // And end to end against the filesystem: a directory where a catalog
        // was expected is a read error, not a missing file, and still yields
        // None so the search continues.
        let dir = std::env::temp_dir().join("freemkv-i18n-try-load-test");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(dir.join("xx.json")).expect("create test dir");
        assert!(try_load(&dir.join("xx.json")).is_none());
        std::fs::write(dir.join("yy.json"), r#"{"app":{"opt_quiet":"q"}}"#).unwrap();
        assert_eq!(
            try_load(&dir.join("yy.json")).and_then(|v| lookup_in(&v, "app.opt_quiet")),
            Some("q".to_string())
        );
        std::fs::write(dir.join("zz.json"), "{ not json").unwrap();
        assert!(try_load(&dir.join("zz.json")).is_none());
        assert!(try_load(&dir.join("absent.json")).is_none());
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// Catches the per-key English fallback being completely silent, and
    /// catches a "log it" fix that floods instead: each distinct key is
    /// reported exactly once, so the line count equals the size of the gap.
    #[test]
    fn a_silently_substituted_english_string_is_reported_once_per_key() {
        assert!(
            report_missing_translation("test.first_key"),
            "the first substitution for a key must be reported"
        );
        assert!(
            !report_missing_translation("test.first_key"),
            "repeats of the same key must not flood the terminal"
        );
        assert!(
            report_missing_translation("test.second_key"),
            "a different key is a different gap and must be reported"
        );
    }

    /// Catches the English catalog being re-parsed on every miss, and catches
    /// the short-circuit being wrong: when English is already active, a miss
    /// must return the path, exactly as a second walk of the same tree would.
    #[test]
    fn the_english_catalog_is_parsed_once_and_skipped_when_active() {
        assert!(
            std::ptr::eq(english_catalog(), english_catalog()),
            "en.json must be parsed once and cached, not re-parsed per miss"
        );

        let sparse: Value = serde_json::json!({ "error": { "E9999": "present" } });
        assert!(lookup_or_english(&sparse, "error.E9053", false).contains("mkv://"));
        assert_eq!(
            lookup_or_english(&sparse, "error.E9053", true),
            "error.E9053",
            "with English active the fallback is a second walk of the same tree"
        );
    }

    /// Catches sequential `String::replace` over the accumulating result: a
    /// substituted value that itself looks like a placeholder was rewritten by
    /// the next argument's pass, so disc-derived text was being read as format
    /// syntax.
    #[test]
    fn substitution_is_single_pass_over_the_original() {
        let out = fmt(
            "error.open_failed",
            &[("device", "{error}"), ("error", "permission denied")],
        );
        assert!(
            out.contains("{error}"),
            "a value that looks like a placeholder must be copied out verbatim: '{out}'"
        );
        assert!(out.contains("permission denied"));
        assert_eq!(
            out.matches("permission denied").count(),
            1,
            "the substituted value was rescanned: '{out}'"
        );

        // A placeholder with no argument is left visible; an unbalanced or
        // nested brace is a literal.
        assert_eq!(substitute("a {x} b", |_| None), "a {x} b");
        assert_eq!(substitute("a {x} b", |_| Some("Z")), "a Z b");
        assert_eq!(substitute("{unclosed", |_| Some("Z")), "{unclosed");
        assert_eq!(substitute("{a{b}", |_| Some("Z")), "{aZ");
        assert_eq!(substitute("", |_| Some("Z")), "");
    }

    #[test]
    fn placeholders_matches_what_fmt_substitutes() {
        assert_eq!(placeholders("hi {name}!"), vec!["{name}".to_string()]);
        assert_eq!(placeholders("a {x} b {y}"), vec!["{x}", "{y}"]);
        assert!(placeholders("no placeholders").is_empty());
        // Every placeholder the helper reports must be one `fmt` really
        // substitutes — the two used to be separate parsers with different
        // rules about doubled braces.
        for s in ["{a}{b}", "{{x}}", "{a{b}", "{unclosed", "plain"] {
            for ph in placeholders(s) {
                let name = &ph[1..ph.len() - 1];
                assert_ne!(
                    substitute(s, |n| (n == name).then_some("SUBSTITUTED")),
                    s,
                    "helper reported {ph} in {s:?} but fmt does not substitute it"
                );
            }
        }
    }

    #[test]
    fn every_shipped_locale_has_full_key_coverage() {
        // Auto-covers every locale file (incl. regional variants) so a new
        // catalog can't ship with missing keys, dropped placeholders, invented
        // placeholders, a non-string value or a blank one. This supersedes the
        // six per-language `locale_XX_loads` tests that used to sit here and
        // checked a hand-picked subset of what this loop already covers.
        assert!(
            SHIPPED_CODES.len() > 1,
            "build.rs bundled nothing but English"
        );
        for code in SHIPPED_CODES {
            if *code == "en" {
                continue;
            }
            let data = bundled_locale_json(code)
                .unwrap_or_else(|| panic!("{code} in SHIPPED_CODES but not bundled"));
            verify_locale(code, data);
        }
    }

    #[test]
    fn locale_en_loads() {
        let _: Value = serde_json::from_str(LOCALE_EN).expect("en.json invalid");
    }

    /// The placeholder-leak fix. `error_message` (no argument) must DROP every
    /// unfilled placeholder — `{detail}`, `{hash}`, `{path}` — and tidy the
    /// punctuation and empty delimiters that leaves; `error_message_with` fills
    /// `{detail}` and drops the rest. Nothing braces-shaped may reach the user.
    ///
    /// Mutation: reverting `error_message` to `get("error.E{code}")` renders the
    /// literal `{detail}`/`{hash}`/`{path}` to the user and fails the leaks.
    #[test]
    fn error_message_drops_unfilled_placeholders_and_with_fills_detail() {
        // The drop-all-then-tidy path, driven directly so the checks do not
        // hinge on which catalog another test in this binary installed.
        let drop = |s: &str| tidy_empty_slots(&substitute(s, |_| Some("")));
        assert_eq!(
            drop("Could not read the disc at sector {detail}. Clean it."),
            "Could not read the disc at sector. Clean it."
        );
        assert_eq!(drop("Drive reset failed: {detail}"), "Drive reset failed");
        assert_eq!(
            drop("The drive is not ready ({detail}). Insert a disc."),
            "The drive is not ready. Insert a disc."
        );
        assert_eq!(
            drop("Title {detail} doesn't exist."),
            "Title doesn't exist."
        );
        assert_eq!(
            drop("Key database download failed (HTTP {detail}). Try again."),
            "Key database download failed (HTTP). Try again."
        );
        // The sibling placeholders: E7022's `(id: {hash})` wrapper and
        // E9067/E9068's quoted `'{path}'` must vanish cleanly, not leave `(id:)`
        // or `''` behind.
        assert_eq!(
            drop("No key source has a decryption key for this disc (id: {hash})."),
            "No key source has a decryption key for this disc."
        );
        assert_eq!(
            drop("A file name is too long. Shorten it and try again: '{path}'."),
            "A file name is too long. Shorten it and try again."
        );
        assert_eq!(drop("plain sentence."), "plain sentence.");

        // Full-width CJK parentheses (ja/zh wrap the value in （）/（id：）, not
        // ASCII parens). An ASCII-only tidy would leave a bare `（）`/`（id：）`.
        assert_eq!(
            drop("ドライブの準備ができていません（{detail}）。挿入してください。"),
            "ドライブの準備ができていません。挿入してください。"
        );
        assert_eq!(
            drop("ダウンロードに失敗しました（HTTP {detail}）。"),
            "ダウンロードに失敗しました（HTTP）。"
        );
        assert_eq!(
            drop("このディスクの復号キーを持つキーソースがありません（id：{hash}）。"),
            "このディスクの復号キーを持つキーソースがありません。"
        );

        // Public entry points. error_message_with fills {detail}; error_message
        // and the {hash}/{path} codes leak nothing.
        let filled = error_message_with(1000, "/dev/sr0");
        assert!(
            filled.contains("/dev/sr0") && !filled.contains("{detail}"),
            "error_message_with must substitute the detail: {filled}"
        );
        for code in [1000u32, 7022, 9067, 9068] {
            let bare = error_message(code);
            assert!(
                !bare.contains('{'),
                "error_message({code}) leaked a placeholder: {bare}"
            );
        }
    }

    /// Three-letter ISO 639-2/3 codes and macrolanguage members fold onto the
    /// shipped two-letter catalog codes.
    ///
    /// Mutation: deleting the `fold_language` call sends `deu` and `nb` to
    /// English despite `de.json`/`no.json` shipping.
    #[test]
    fn normalize_code_folds_three_letter_and_macrolanguage_codes() {
        assert_eq!(normalize_code("deu"), "de");
        assert_eq!(normalize_code("ger"), "de"); // 639-2/B alias
        assert_eq!(normalize_code("fra"), "fr");
        assert_eq!(normalize_code("fre"), "fr");
        assert_eq!(normalize_code("spa"), "es");
        assert_eq!(normalize_code("nld"), "nl");
        assert_eq!(normalize_code("jpn"), "ja");
        assert_eq!(normalize_code("rus"), "ru");
        assert_eq!(normalize_code("deu_DE"), "de-de");
        // Norwegian: nb/nn have no catalog of their own; the shipped one is `no`.
        assert_eq!(normalize_code("nb"), "no");
        assert_eq!(normalize_code("nn"), "no");
        assert_eq!(normalize_code("nb_NO.UTF-8"), "no-no");
        assert_eq!(normalize_code("mo"), "ro"); // deprecated Moldovan alias
        // An unshipped 3-letter code is passed through untouched (→ English).
        assert_eq!(normalize_code("swa"), "swa");
    }

    /// Extended-language subtags resolve to the extlang, not to the macro
    /// language's default script.
    ///
    /// Mutation: dropping the extlang promotion lets Chinese inference fold the
    /// bare `zh` onto Simplified, so `zh-yue` (Cantonese) silently becomes
    /// Simplified Mandarin — a different language.
    #[test]
    fn normalize_code_handles_extended_language_subtags() {
        assert_eq!(normalize_code("zh-yue"), "yue");
        assert_eq!(normalize_code("zh_yue_HK"), "yue-hk");
        // A Mandarin extlang folds to `zh` and picks up Simplified by default.
        assert_eq!(normalize_code("zh-cmn"), "zh-hans");
        assert_eq!(normalize_code("zh-cmn-Hant"), "zh-hant");
        // A 3-DIGIT subtag is a region, never an extlang.
        assert_eq!(normalize_code("es-419"), "es-419");
    }

    /// GNU `LANGUAGE` precedence: a colon-separated priority list that overrides
    /// a real POSIX selection but is IGNORED for the C/POSIX locale.
    ///
    /// Mutation: the old body never read LANGUAGE, so `LANGUAGE=de LANG=en_US`
    /// returned `en_US` (English) instead of German.
    #[test]
    fn gnu_language_overrides_a_real_locale_but_not_the_c_locale() {
        let env = |pairs: &[(&str, &str)]| {
            let owned: Vec<(String, String)> = pairs
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect();
            move |var: &str| {
                owned
                    .iter()
                    .find(|(k, _)| k == var)
                    .map(|(_, v)| v.to_string())
            }
        };
        // Headline: LANGUAGE overrides a real LANG, and the WHOLE colon list is
        // preserved in order (a "first entry only" reading would drop `en`).
        assert_eq!(
            locale_candidates_from_env(env(&[("LANGUAGE", "de:en"), ("LANG", "en_US.UTF-8")])),
            vec!["de", "en"]
        );
        // Empty entries are skipped; each entry is normalized.
        assert_eq!(
            locale_candidates_from_env(env(&[("LANGUAGE", ":fr:pt_BR"), ("LANG", "en_US.UTF-8")])),
            vec!["fr", "pt-br"]
        );
        // LC_ALL=C must NOT be overridden — parseable-output contract.
        assert_eq!(
            locale_candidates_from_env(env(&[("LC_ALL", "C"), ("LANGUAGE", "de:en")])),
            vec!["en"]
        );
        // LANGUAGE with no locale variable set is ignored (that is the C locale).
        assert_eq!(
            locale_candidates_from_env(env(&[("LANGUAGE", "de")])),
            vec!["en"]
        );
        // An empty LANGUAGE falls back to the POSIX selection.
        assert_eq!(
            locale_candidates_from_env(env(&[("LANGUAGE", ""), ("LANG", "it_IT")])),
            vec!["it-it"]
        );
    }

    /// The GNU `LANGUAGE` list is tried entry by entry: a leading entry with no
    /// catalog must not short-circuit to English before a later, shipped entry.
    ///
    /// Mutation: resolving only `candidates[0]` renders `sw:de` as English even
    /// though `de.json` ships.
    #[test]
    fn language_priority_list_tries_each_entry_before_english() {
        let de: Value = serde_json::from_str(bundled_locale_json("de").unwrap()).unwrap();
        let (got, is_en) = resolve_catalog_for_candidates(&["sw".to_string(), "de".to_string()]);
        assert_eq!(
            got, de,
            "sw:de must reach German, not stop at the first miss"
        );
        assert!(!is_en);
        // Every candidate missing → English.
        let (fallback, en_flag) =
            resolve_catalog_for_candidates(&["sw".to_string(), "xx".to_string()]);
        assert_eq!(fallback, *english_catalog());
        assert!(en_flag);
    }

    /// A blank locale value is a translation hole that reads as success.
    ///
    /// Mutation: returning `lookup_in`'s `Some("")` unconditionally renders an
    /// empty message under a non-English locale instead of the English text.
    #[test]
    fn a_blank_locale_value_is_treated_as_missing() {
        let blank: Value = serde_json::json!({ "error": { "E9053": "   " } });
        let got = lookup_or_english(&blank, "error.E9053", false);
        assert!(
            got.contains("mkv://"),
            "a blank value must fall back to English, got {got:?}"
        );
        // Blank with English already active degrades to the path, not "".
        let both: Value = serde_json::json!({ "x": "" });
        assert_eq!(lookup_or_english(&both, "x", true), "x");
    }

    #[test]
    fn open_failed_key_exists_and_fills_placeholders() {
        // Regression: `error.open_failed` was referenced by the drive-info /
        // CLI device-open path but never defined in any locale. A missing key
        // makes `lookup` return the dotted path verbatim, so `fmt` had no
        // `{device}`/`{error}` to substitute and the user saw the bare string
        // "error.open_failed". Guard that the key exists with both placeholders.
        let val = lookup_or_english(english_catalog(), "error.open_failed", true);
        assert_ne!(
            val, "error.open_failed",
            "error.open_failed missing from en.json (lookup returned the key verbatim)"
        );
        let ph = placeholders(&val);
        assert!(
            ph.contains(&"{device}".to_string()) && ph.contains(&"{error}".to_string()),
            "error.open_failed must contain {{device}} and {{error}} placeholders, got: '{}'",
            val
        );

        // And the full fmt() path produces a clean message with the values
        // substituted and no leftover placeholders or bare key.
        let out = fmt(
            "error.open_failed",
            &[("device", "/dev/sg0"), ("error", "permission denied")],
        );
        assert!(
            out.contains("/dev/sg0"),
            "device not substituted: '{}'",
            out
        );
        assert!(
            out.contains("permission denied"),
            "error not substituted: '{}'",
            out
        );
        assert!(!out.contains("{device}") && !out.contains("{error}"));
        assert_ne!(out, "error.open_failed");
    }

    #[test]
    fn bundled_locale_json_returns_every_shipped_language() {
        // Every code build.rs bundled must resolve to parseable JSON, and an
        // unknown code must return None (it would be sought on disk at runtime
        // instead). This used to name seven languages by hand; 29 bundle.
        for code in SHIPPED_CODES {
            let data =
                bundled_locale_json(code).unwrap_or_else(|| panic!("{code} should be bundled"));
            let _: Value =
                serde_json::from_str(data).unwrap_or_else(|e| panic!("{code}.json invalid: {e}"));
        }
        assert!(bundled_locale_json("zz").is_none());
        // build.rs derives the bundled code with the same `normalize_code` the
        // runtime resolves with, so every shipped code is reachable from a tag.
        for code in SHIPPED_CODES {
            assert_eq!(
                normalize_code(code),
                **code,
                "{code} is bundled under a code no tag normalizes to"
            );
        }
    }

    /// Catches `.unwrap()` on the catalog lock.
    ///
    /// A panic anywhere in the program while the write lock is held poisons it,
    /// and an unwrapping accessor then turns that into a panic in EVERY later
    /// string lookup — including the one the panic handler itself makes while
    /// trying to render the original error. The user loses the real failure and
    /// gets a lock-poisoning backtrace in its place. The data behind the lock is
    /// a parsed catalog that a panic cannot leave half-written, so recovering
    /// the guard is both safe and strictly better than aborting the run.
    ///
    /// This deliberately poisons the process-wide lock and leaves it poisoned:
    /// with the fix in place nothing else notices, which is the entire point.
    #[test]
    fn a_poisoned_catalog_lock_does_not_take_the_process_down() {
        let poisoner = std::thread::spawn(|| {
            let _guard = write_strings();
            panic!("simulated panic while holding the catalog lock");
        });
        assert!(poisoner.join().is_err(), "the poisoning thread must panic");
        assert!(STRINGS.is_poisoned(), "the lock must actually be poisoned");

        // Both accessors, and the whole public read path on top of them, keep
        // working.
        drop(read_strings());
        drop(write_strings());
        assert_ne!(
            get("error.open_failed"),
            "error.open_failed",
            "a lookup after a poisoned lock must still return a real message"
        );
    }

    /// Catches a second `--language` being dropped into `let _ = ...set(..)`
    /// with nothing said about it.
    #[test]
    fn a_second_language_override_is_reported_not_swallowed() {
        let msg = language_override_conflict("fr", Some("de")).expect("conflict must be reported");
        assert!(msg.contains("fr") && msg.contains("de"), "{msg}");
        // Asking twice for the same language changed nothing, so there is
        // nothing to warn about.
        assert_eq!(language_override_conflict("de", Some("de")), None);
        assert_eq!(language_override_conflict("de", None), None);
    }

    /// The empty-candidate-list edge of the "not found" diagnostic: when there
    /// is no first candidate at all (as opposed to one that missed), the match
    /// must fall through quietly rather than panic on `.first()` or print a
    /// diagnostic naming nothing.
    #[test]
    fn resolve_catalog_for_candidates_with_no_candidates_falls_back_to_english_silently() {
        let (got, is_en) = resolve_catalog_for_candidates(&[]);
        assert_eq!(got, *english_catalog());
        assert!(is_en);
    }

    /// A GNU `LANGUAGE` value that is present but resolves to no usable
    /// candidates (every entry empty, e.g. a bare `:`) must fall through to the
    /// POSIX selection instead of returning an empty candidate list.
    #[test]
    fn language_var_with_only_empty_entries_falls_through_to_posix_selection() {
        let env = |pairs: &[(&str, &str)]| {
            let owned: Vec<(String, String)> = pairs
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect();
            move |var: &str| {
                owned
                    .iter()
                    .find(|(k, _)| k == var)
                    .map(|(_, v)| v.to_string())
            }
        };
        assert_eq!(
            locale_candidates_from_env(env(&[("LANGUAGE", ":"), ("LANG", "it_IT")])),
            vec!["it-it"]
        );
    }

    /// `load_locale_file` against the real, unmocked search path: it must find
    /// and parse a catalog dropped in `./locales` (the working-directory search
    /// path every consumer relies on), not just the bundled/compiled-in ones
    /// the rest of the suite exercises.
    #[test]
    fn load_locale_file_finds_a_catalog_via_the_real_working_directory_search_path() {
        let path = Path::new("locales/ztx.json");
        std::fs::write(path, r#"{"app":{"opt_quiet":"disk-loaded"}}"#)
            .expect("write test locale file");
        let result = load_locale_file("ztx");
        let _ = std::fs::remove_file(path);
        let v = result.expect("must find the file just written under ./locales");
        assert_eq!(
            lookup_in(&v, "app.opt_quiet"),
            Some("disk-loaded".to_string())
        );
    }

    #[test]
    fn error_message_returns_real_string_not_key_path() {
        // E7022 ("no key source has a decryption key for this disc") is a known
        // code present in en.json. error_message must return its actual string,
        // not the `error.E7022` miss sentinel. Its English string names the disc
        // by `{hash}` — a value this bare-code entry point does not have — so the
        // placeholder must be DROPPED (with its `(id: …)` wrapper), never leaked
        // as literal `{hash}` the way it once was on autorip's code-only path.
        // (This assertion used to require `{hash}` to be preserved; that pinned
        // the very leak the round-2 audit removed.)
        let msg = error_message(7022);
        assert_ne!(
            msg, "error.E7022",
            "error_message(7022) returned the key path — the string is missing or the key format is wrong"
        );
        assert!(
            !msg.contains('{'),
            "error_message(7022) leaked a placeholder to the user, got: '{msg}'"
        );
        assert!(
            !msg.contains("(id:)") && !msg.contains("（id：）"),
            "error_message(7022) left an empty (id:) wrapper: '{msg}'"
        );
        assert!(
            msg.contains("decryption key"),
            "error_message(7022) lost its real wording: '{msg}'"
        );

        // E1000 (drive not found) is another known code; sanity-check it too.
        assert_ne!(error_message(1000), "error.E1000");

        // An unknown code falls back to the key path (same miss behavior as get).
        assert_eq!(error_message(999_999), "error.E999999");
    }

    /// The key-SOURCE failure codes must each render as their own message, and
    /// none of them may render as E7022's "no key source has a key for this
    /// disc". That sentence is what an operator read during a seven-hour HTTP 502
    /// outage before going to hunt for a VUK that was never missing — the three
    /// codes exist precisely so the outage does not borrow it.
    #[test]
    fn key_service_failure_codes_do_not_reuse_the_missing_key_wording() {
        let missing_key = error_message(7022);
        let mut seen = Vec::new();
        for code in [7028u32, 7029, 7030] {
            let msg = error_message(code);
            assert_ne!(
                msg,
                format!("error.E{code}"),
                "E{code} has no English string"
            );
            assert_ne!(
                msg, missing_key,
                "E{code} must not reuse E7022's missing-key wording"
            );
            assert!(
                !seen.contains(&msg),
                "E{code} duplicates another code's text"
            );
            seen.push(msg);
        }
    }
}

#[cfg(test)]
mod fallback_tests {
    use super::*;

    /// A key present in English but missing from the active locale must render
    /// the ENGLISH text, never the raw path.
    ///
    /// Before the per-key fallback, `lookup` returned the path itself, so a user
    /// under a non-English locale saw the literal string `error.E9053` where a
    /// message belonged. Five error codes added during the 1.6.0 audit were in
    /// exactly that state — and two of them exist because that audit split apart
    /// codes that had been reporting total failure as success, so the fix that
    /// made those failures visible would have shown an internal key.
    #[test]
    fn a_key_missing_from_the_locale_falls_back_to_english() {
        // A catalog that deliberately lacks the key.
        let sparse: Value = serde_json::json!({ "error": { "E9999": "present" } });
        let got = lookup_or_english(&sparse, "error.E9053", false);
        assert_ne!(
            got, "error.E9053",
            "a missing key must not render as its own path"
        );
        assert!(
            got.contains("mkv://"),
            "expected the English text for E9053, got {got:?}"
        );
        // A key missing from BOTH still degrades to the path — there is nothing
        // better to show, and silently returning empty would be worse.
        assert_eq!(
            lookup_or_english(&sparse, "error.E0000", false),
            "error.E0000"
        );
    }
}

#[cfg(test)]
mod error_code_coverage {
    use super::error_codes::LIBFREEMKV_ERROR_CODES;
    use super::*;

    /// EVERY error code libfreemkv can raise must have a non-empty English
    /// string.
    ///
    /// This is the check that was absent. `error_message` takes a bare `u32`
    /// with nothing to enumerate, so the only guard was a handful of
    /// hand-written code literals in tests: a new libfreemkv code shipped, no
    /// string was ever written for it, and it rendered to the user as the
    /// literal text `error.E12345` forever while fmt, clippy and the test suite
    /// all stayed green. The CHANGELOG records this happening — "five codes
    /// shipped without one because nothing compared the two lists". At the time
    /// this check was added ELEVEN more codes were in that state, including
    /// E9056/E9057, which report that a rip could not be confirmed written to
    /// disk.
    ///
    /// The two lists are compared mechanically now. The list is checked in
    /// rather than read from libfreemkv, because this crate must not depend on
    /// it: libfreemkv pulls in freemkv-unlock, which is private and never
    /// published, so a dependency here would make this crate unbuildable in its
    /// own CI (which deliberately checks out no siblings) and would invert the
    /// layering — libfreemkv emits codes, this crate renders them.
    /// `libfreemkv_code_list_has_not_drifted` keeps the checked-in copy honest.
    #[test]
    fn libfreemkv_error_codes_all_have_english_strings() {
        let en = english_catalog();
        let mut missing = Vec::new();
        for (code, name) in LIBFREEMKV_ERROR_CODES {
            let key = format!("error.E{code}");
            match lookup_in(en, &key) {
                Some(s) if !s.trim().is_empty() => {}
                _ => missing.push(format!("E{code} ({name})")),
            }
        }
        assert!(
            missing.is_empty(),
            "{} libfreemkv error code(s) have no English string in en.json, so they \
             render to the user as the literal key path: {:?}",
            missing.len(),
            missing
        );
    }

    /// The reverse direction: an `error.EXXXX` key in en.json that matches no
    /// libfreemkv code is either a typo (so the real code still has no string)
    /// or a retired code that translators keep maintaining.
    #[test]
    fn en_json_has_no_error_key_for_a_code_that_does_not_exist() {
        let en = english_catalog();
        let known: Vec<u32> = LIBFREEMKV_ERROR_CODES.iter().map(|(c, _)| *c).collect();
        let mut orphans = Vec::new();
        for key in en["error"].as_object().expect("error block").keys() {
            if let Some(digits) = key.strip_prefix('E')
                && let Ok(code) = digits.parse::<u32>()
                && !known.contains(&code)
            {
                orphans.push(key.clone());
            }
        }
        assert!(
            orphans.is_empty(),
            "en.json has error string(s) for code(s) libfreemkv cannot raise: {orphans:?}"
        );
    }

    /// Catches the checked-in list going stale against the real libfreemkv.
    ///
    /// Only runs where a sibling libfreemkv checkout exists — a developer
    /// machine and the front-end repos' CI, never this crate's own CI, which
    /// checks out nothing else. That is the trade for not taking the
    /// dependency: CI enforces "every code in the list has a string" always,
    /// and "the list is the real list" wherever the real list is on disk.
    #[test]
    fn libfreemkv_code_list_has_not_drifted() {
        let source = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../libfreemkv/src/error.rs")
            .canonicalize();
        let Ok(source) = source else {
            eprintln!("libfreemkv checkout not present; skipping error-code drift check");
            return;
        };
        let Ok(text) = std::fs::read_to_string(&source) else {
            eprintln!("libfreemkv error.rs unreadable; skipping error-code drift check");
            return;
        };

        let mut actual: Vec<(u32, String)> = Vec::new();
        for line in text.lines() {
            let line = line.trim();
            let Some(rest) = line.strip_prefix("pub const E_") else {
                continue;
            };
            let Some((name, value)) = rest.split_once(": u16 = ") else {
                continue;
            };
            if let Ok(code) = value.trim_end_matches(';').trim().parse::<u32>() {
                actual.push((code, format!("E_{name}")));
            }
        }
        actual.sort();
        assert!(
            !actual.is_empty(),
            "parsed no codes out of {} — the const shape changed and this test \
             would otherwise pass vacuously",
            source.display()
        );

        let mut checked_in: Vec<(u32, String)> = LIBFREEMKV_ERROR_CODES
            .iter()
            .map(|(c, n)| (*c, n.to_string()))
            .collect();
        checked_in.sort();

        assert_eq!(
            checked_in,
            actual,
            "src/error_codes.rs is out of date with {}. Regenerate it:\n    \
             ci/sync-error-codes.sh\nthen add an English string (and a line in \
             every locale) for any new code.",
            source.display()
        );
    }
}
