// freemkv-i18n — i18n string loader, MIT, freemkv project.

use serde_json::Value;
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Mutex, OnceLock, RwLock, RwLockReadGuard, RwLockWriteGuard};

mod locale_code;
use locale_code::{fallback_chain, locale_filenames, normalize_code};

// The catalog the error-code registry test compares against. Checked in and
// regenerated by ci/sync-error-codes.sh — see the module comment for why this
// crate cannot simply depend on libfreemkv.
#[cfg(test)]
mod error_codes;

// RwLock (not OnceLock): a GUI can switch language live via set_locale, while
// the CLI sets it once at startup. None until first use, lazily initialized.
static STRINGS: RwLock<Option<Value>> = RwLock::new(None);
static LANG_OVERRIDE: OnceLock<String> = OnceLock::new();
// Whether STRINGS is currently the English catalog, so a miss can skip the
// redundant per-key English fallback walk. Written under the same write lock.
static ACTIVE_IS_EN: AtomicBool = AtomicBool::new(false);

static INIT_LOCK: Mutex<()> = Mutex::new(());

fn init_lock() -> std::sync::MutexGuard<'static, ()> {
    INIT_LOCK.lock().unwrap_or_else(|e| e.into_inner())
}

// ── Shipped languages (auto-generated from locales/*.json by build.rs) ─────
include!(concat!(env!("OUT_DIR"), "/locales_generated.rs"));

// ── Lock access ────────────────────────────────────────────────────────────.

fn read_strings() -> RwLockReadGuard<'static, Option<Value>> {
    STRINGS.read().unwrap_or_else(|e| e.into_inner())
}

fn write_strings() -> RwLockWriteGuard<'static, Option<Value>> {
    STRINGS.write().unwrap_or_else(|e| e.into_inner())
}

/// Set language override from --language flag. Call before init().
///
/// This is the one-shot pre-init override; use [`set_locale`] to change
/// language while the program is running.
///
/// Once `init()`/`get()` has locked in the active locale (`STRINGS`), this
/// override is dead: the language is already chosen. A call at that point is a
/// caller-ordering bug, so make it visible instead of silently no-opping.
pub fn set_language(lang: &str) {
    // Whole check-then-set under INIT_LOCK,.
    let _init = init_lock();
    let guard = read_strings();
    if guard.is_some() {
        debug_assert!(
            false,
            "set_language(\"{lang}\") called after strings were initialized; use set_locale to switch live"
        );
        eprintln!("warning: --language ignored (set after locale was initialized)");
        return;
    }
    if LANG_OVERRIDE.set(lang.to_string()).is_err()
        && let Some(msg) = language_override_conflict(lang, LANG_OVERRIDE.get().map(String::as_str))
    {
        // A second `--language` used to vanish into `let _ = ...set(..)`. The
        // first one wins, which is a defensible rule, but the user asked for
        // something they did not get and nothing said so.
        eprintln!("{msg}");
    }
}

/// The warning for a `--language` override that arrived after one was already
/// locked in, or `None` when there is nothing worth saying (the same language
/// requested twice changes nothing).
fn language_override_conflict(requested: &str, existing: Option<&str>) -> Option<String> {
    let existing = existing?;
    (existing != requested).then(|| {
        format!(
            "warning: --language {requested} ignored; the language was already set to {existing}"
        )
    })
}

/// Switch the active locale at runtime — the live path a GUI language change
/// uses. Unlike [`set_language`] (a one-shot pre-init override), this
/// re-resolves and swaps the catalog in place, so subsequent `get`/`fmt` calls
/// return the new language without a restart. `code` is any locale string
/// (`"de"`, `"pt-BR"`, `"auto"`); it is normalized and resolved the same way as
/// startup (full tag → language+script → base language → English). Safe to call
/// repeatedly.
pub fn set_locale(code: &str) {
    // INIT_LOCK across resolve-then-install so the last CALLER wins, not the last resolve to
    // finish.
    let _init = init_lock();
    // "auto" re-detects from the environment, exactly like startup (init()),
    // rather than normalizing the literal string "auto" (which resolves to
    // nothing and would silently fall back to English).
    let (resolved, is_english) = if code.eq_ignore_ascii_case("auto") {
        resolve_catalog_for_candidates(&detect_languages())
    } else {
        resolve_catalog_tagged(&normalize_code(code))
    };
    let mut w = write_strings();
    ACTIVE_IS_EN.store(is_english, Ordering::Relaxed);
    *w = Some(resolved);
}

/// Initialize strings for the current locale (CLI startup). Idempotent-ish: it
/// (re)resolves from the environment / `--language` override and installs the
/// catalog. `get`/`fmt` also initialize lazily, so calling this is optional.
pub fn init() {
    // Serialize with the other installing paths (see INIT_LOCK) so a concurrent
    // `set_language` cannot land between this resolve and its install.
    let _init = init_lock();
    let (json, is_english) = resolve_catalog_for_candidates(&detect_languages());
    let mut w = write_strings();
    ACTIVE_IS_EN.store(is_english, Ordering::Relaxed);
    *w = Some(json);
}

// Resolve a single code via fallback_chain (see below), plus whether the
// result is the English catalog. Used by set_locale and the tests.
fn resolve_catalog_tagged(code: &str) -> (Value, bool) {
    resolve_catalog_for_candidates(std::slice::from_ref(&code.to_string()))
}

// Resolve an ordered candidate list (GNU LANGUAGE list, or a single code):
// each candidate's whole prefix chain is tried before moving to the next, so
// LANGUAGE=sw:de reaches German instead of stopping at the first miss.
fn resolve_catalog_for_candidates(candidates: &[String]) -> (Value, bool) {
    for candidate in candidates {
        for step in fallback_chain(candidate) {
            if let Some(v) = load_for(&step) {
                return (v, step == "en");
            }
        }
    }
    // Notify the user when they explicitly requested a locale that isn't
    // available (VAL-3). Plain English is intentional here. The first candidate
    // is the one the user most wanted, so it is the one worth naming.
    match candidates.first() {
        Some(first) if first != "en" => {
            eprintln!("freemkv: locale '{first}' not found, using English");
        }
        _ => {}
    }
    (english_catalog().clone(), true)
}

/// Load one locale code: compiled-in first, then disk search paths. `None` if
/// that exact code has no catalog anywhere (the caller then tries the next,
/// less specific code in the fallback chain, then English).
fn load_for(code: &str) -> Option<Value> {
    if let Some(data) = bundled_locale(code) {
        // Parse failure here should be unreachable (build.rs validates it), but
        // `expect` would be a landmine in the crate whose job is rendering
        // errors. Log and fall through to the next fallback candidate instead.
        return match serde_json::from_str(data) {
            Ok(v) => Some(v),
            Err(e) => {
                eprintln!("freemkv: bundled locale '{code}' failed to parse ({e}); ignoring it");
                None
            }
        };
    }
    load_locale_file(code)
}

/// Get a string by dotted path (e.g. "disc.scanning", "error.no_drive").
///
/// A key present in the active locale renders its value. A key present in
/// English but missing (or blank) in the active locale falls back to the
/// English string, reported once (see [`lookup_or_english`]). Only a key that
/// exists in NO catalog renders as the dotted path itself, which keeps a truly
/// missing translation visible rather than blank.
pub fn get(path: &str) -> String {
    // Fast path: catalog already loaded — take the read lock and look up.
    {
        let guard = read_strings();
        if let Some(v) = guard.as_ref() {
            return lookup_or_english(v, path, ACTIVE_IS_EN.load(Ordering::Relaxed));
        }
    }
    // First use with no explicit init(): resolve and install under INIT_LOCK  so a concurrent
    // set_language/set_locale can't race.
    let _init = init_lock();
    // Another thread may have installed a catalog while we waited; use it
    // rather than resolving and installing a second time.
    {
        let guard = read_strings();
        if let Some(v) = guard.as_ref() {
            return lookup_or_english(v, path, ACTIVE_IS_EN.load(Ordering::Relaxed));
        }
    }
    let (json, is_english) = resolve_catalog_for_candidates(&detect_languages());
    let mut w = write_strings();
    ACTIVE_IS_EN.store(is_english, Ordering::Relaxed);
    *w = Some(json);
    let active = w.as_ref().unwrap_or_else(|| english_catalog());
    lookup_or_english(active, path, ACTIVE_IS_EN.load(Ordering::Relaxed))
}

/// Get a string and replace `{key}` placeholders with values.
///
/// Substitution is a single pass over the catalog string, so a substituted value that itself
/// looks like a placeholder is never rescanned. A `{` that does not open a well-formed `{name}`
/// is a literal `{`, and a `{name}` with no matching argument is left in place (visible, so a
/// caller that forgot an argument is caught).
pub fn fmt(path: &str, args: &[(&str, &str)]) -> String {
    substitute(&get(path), |name| {
        args.iter().find(|(k, _)| *k == name).map(|(_, v)| *v)
    })
}

// The one and only placeholder scanner: `resolve` is called with each
// placeholder name, `None` leaves it untouched. Tests reuse this scanner too,
// so the cross-locale placeholder check can't drift from what fmt does.
fn substitute<'a>(s: &str, mut resolve: impl FnMut(&str) -> Option<&'a str>) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(open) = rest.find('{') {
        out.push_str(&rest[..open]);
        let after = &rest[open + 1..];
        match after.find('}') {
            // A real placeholder is a balanced `{...}` with no nested brace.
            Some(close) if !after[..close].contains('{') => {
                let name = &after[..close];
                match resolve(name) {
                    Some(value) => out.push_str(value),
                    None => {
                        out.push('{');
                        out.push_str(name);
                        out.push('}');
                    }
                }
                rest = &after[close + 1..];
            }
            _ => {
                out.push('{');
                rest = after;
            }
        }
    }
    out.push_str(rest);
    out
}

/// Look up the localized message for a libfreemkv error code, WITHOUT any
/// argument. Error strings live under `error.E<code>`, matching
/// `libfreemkv::Error::code()`.
///
/// Some codes have a placeholder (`{detail}`, `{hash}`, `{path}`) that only a caller holding
/// the originating error can fill; this entry point DROPS every unfilled placeholder rather
/// than leaking it. Use [`error_message_with`] when the detail is available. Falls back to the
/// key path — same miss behavior as [`get`].
pub fn error_message(code: u32) -> String {
    render_error_message(code, None)
}

/// Look up the localized message for a libfreemkv error code and substitute
/// the `{detail}` placeholder with `detail`.
///
/// The detail-preserving companion to [`error_message`]: a caller holding the
/// originating `libfreemkv::Error` (device path, failing sector, HTTP status,
/// URL, …) should call this so the value reaches the user. A string with no
/// `{detail}` ignores the argument. Any OTHER unfilled placeholder (`{hash}`,
/// `{path}`) is dropped, exactly as in [`error_message`].
pub fn error_message_with(code: u32, detail: &str) -> String {
    render_error_message(code, Some(detail))
}

// Render error.E<code>, filling {detail} when Some and dropping every other
// placeholder, then tidying the punctuation the drop leaves behind.
fn render_error_message(code: u32, detail: Option<&str>) -> String {
    let raw = get(&format!("error.E{code}"));
    if !raw.contains('{') {
        // No placeholder, or the key-path miss — nothing to fill/drop/tidy.
        return raw;
    }
    let filled = substitute(&raw, |name| match (name, detail) {
        ("detail", Some(d)) => Some(d),
        // Unfilled placeholders are removed, never left as literal `{name}`.
        _ => Some(""),
    });
    tidy_empty_slots(&filled)
}

fn tidy_empty_slots(s: &str) -> String {
    // A parenthetical whose value was a placeholder now reads as a bare label
    // and colon (`(id:)`, `（id：）`) — drop the whole group, before the space
    // rules below reshuffle it.
    let mut out = drop_colon_only_parentheticals(s);
    // Drop an empty bracket/quote the removed value left, ASCII and
    // full-width, with an ASCII or ideographic space inside.
    for empty in ["( )", "()", "（）", "（ ）", "（\u{3000}）", "''", "\"\""] {
        out = out.replace(empty, "");
    }
    // Remove a space (ASCII or ideographic) now sitting before closing
    // punctuation, or after an opening bracket.
    for (from, to) in [
        (" .", "."),
        (" ,", ","),
        (" :", ":"),
        (" ;", ";"),
        (" !", "!"),
        (" ?", "?"),
        (" )", ")"),
        ("( ", "("),
        (":.", "."),
        (" ）", "）"),
        ("\u{3000}）", "）"),
        ("（ ", "（"),
        ("（\u{3000}", "（"),
    ] {
        while out.contains(from) {
            out = out.replace(from, to);
        }
    }
    // Collapse doubled spaces, then trim, then drop a now-dangling trailing
    // colon (`Drive reset failed:` → `Drive reset failed`).
    while out.contains("  ") {
        out = out.replace("  ", " ");
    }
    let trimmed = out.trim();
    trimmed.strip_suffix(':').unwrap_or(trimmed).to_string()
}

// Remove every parenthetical (ASCII or full-width) whose content is a bare
// label ending in a colon, e.g. E7022's `(id: {hash})` -> `(id:)` after the
// value drops. A real parenthetical has a value after its colon.
fn drop_colon_only_parentheticals(s: &str) -> String {
    let mut out = s.to_string();
    for (open, close) in [("(", ")"), ("（", "）")] {
        let mut search = 0;
        while let Some(rel_open) = out[search..].find(open) {
            let o = search + rel_open;
            let after = o + open.len();
            if let Some(rel_close) = out[after..].find(close) {
                let c = after + rel_close;
                let content = out[after..c].trim();
                if !content.is_empty()
                    && !content.contains(open)
                    && (content.ends_with(':') || content.ends_with('：'))
                {
                    out.replace_range(o..c + close.len(), "");
                    search = 0;
                    continue;
                }
            }
            search = o + open.len();
        }
    }
    out
}

/// Returns the bundled (compiled-in) locale JSON for `code`, if that language
/// is shipped with the crate. Exposed so downstream contract tests can validate
/// locale coverage against the exact bundled data without re-bundling the
/// files themselves (and without relying on a sibling-directory path that only
/// exists in a local checkout).
pub fn bundled_locale_json(code: &str) -> Option<&'static str> {
    bundled_locale(code)
}

// ── Internal ───────────────────────────────────────────────────────────────

// The parsed English catalog, parsed ONCE for the life of the process (the
// per-key fallback used to re-parse the whole 45 KB document on every miss).
fn english_catalog() -> &'static Value {
    static EN: OnceLock<Value> = OnceLock::new();
    EN.get_or_init(|| serde_json::from_str(LOCALE_EN).expect("invalid en.json"))
}

// Ordered catalog codes to try for the environment, most preferred first
// (GNU LANGUAGE list, or the POSIX selection). set_language's override, when
// present, is the whole list.
fn detect_languages() -> Vec<String> {
    if let Some(lang) = LANG_OVERRIDE.get() {
        return vec![normalize_code(lang)];
    }
    locale_candidates_from_env(|var| std::env::var(var).ok())
}

// POSIX precedence: LC_ALL, then LC_MESSAGES, then LANG — the first that is set and non-empty
// wins outright, even when its value is C/POSIX.
fn locale_from_env(get_var: impl Fn(&str) -> Option<String>) -> String {
    ["LC_ALL", "LC_MESSAGES", "LANG"]
        .iter()
        .find_map(|var| get_var(var).filter(|v| !v.is_empty()))
        .unwrap_or_else(|| "en".to_string())
}

// Ordered candidate codes for the environment: GNU LANGUAGE (a colon- separated priority list)
// applied on top of the POSIX selection, but ignored for the C/POSIX locale.
fn locale_candidates_from_env(get_var: impl Fn(&str) -> Option<String>) -> Vec<String> {
    let selected = ["LC_ALL", "LC_MESSAGES", "LANG"]
        .iter()
        .find_map(|var| get_var(var).filter(|v| !v.is_empty()));

    if !is_posix_c_locale(selected.as_deref().unwrap_or("C"))
        && let Some(language) = get_var("LANGUAGE").filter(|v| !v.is_empty())
    {
        let candidates: Vec<String> = language
            .split(':')
            .filter(|entry| !entry.is_empty())
            .map(normalize_code)
            .collect();
        if !candidates.is_empty() {
            return candidates;
        }
    }

    vec![normalize_code(&locale_from_env(&get_var))]
}

// Whether a locale VALUE names the POSIX C locale (C, POSIX, or empty) — checks the raw NAME,
// not normalize_code's output, since en_US also normalizes to English but is a real locale.
fn is_posix_c_locale(val: &str) -> bool {
    let base = val.trim().split(['.', '@']).next().unwrap_or("");
    base.is_empty() || base.eq_ignore_ascii_case("C") || base.eq_ignore_ascii_case("POSIX")
}

// The user's home directory, by whichever variable this platform sets ($HOME
// alone gated search path 3, and stock Windows doesn't set it).
fn home_dir() -> Option<PathBuf> {
    #[cfg(windows)]
    const HOME_VARS: &[&str] = &["USERPROFILE", "HOME"];
    #[cfg(not(windows))]
    const HOME_VARS: &[&str] = &["HOME"];

    HOME_VARS
        .iter()
        .filter_map(std::env::var_os)
        .find(|v| !v.is_empty())
        .map(PathBuf::from)
}

/// The machine-wide locale directory. `/usr/share` has no meaning on Windows,
/// where the equivalent is `%PROGRAMDATA%`.
fn system_locale_dir() -> Option<PathBuf> {
    #[cfg(windows)]
    {
        std::env::var_os("PROGRAMDATA")
            .filter(|v| !v.is_empty())
            .map(|p| PathBuf::from(p).join("freemkv").join("locales"))
    }
    #[cfg(not(windows))]
    {
        Some(PathBuf::from("/usr/share/freemkv/locales"))
    }
}

/// The directories searched for on-disk catalogs, in priority order. Split out
/// from the environment lookups so the ordering and the platform differences
/// can be tested without mutating process-wide state.
fn locale_search_dirs_from(
    exe_dir: Option<PathBuf>,
    home: Option<PathBuf>,
    system: Option<PathBuf>,
) -> Vec<PathBuf> {
    let mut dirs = Vec::with_capacity(4);
    if let Some(dir) = exe_dir {
        dirs.push(dir.join("locales"));
    }
    if let Some(home) = home {
        dirs.push(home.join(".config").join("freemkv").join("locales"));
    }
    if let Some(system) = system {
        dirs.push(system);
    }
    // Lowest precedence: whatever a user/system catalog didn't cover falls
    // back to cwd, but cwd must never override them (VAL-audit: launching
    // from an arbitrary directory must not shadow the installed catalog).
    dirs.push(PathBuf::from("locales"));
    dirs
}

fn locale_search_dirs() -> Vec<PathBuf> {
    let exe_dir = std::env::current_exe()
        .ok()
        .and_then(|exe| exe.parent().map(Path::to_path_buf));
    locale_search_dirs_from(exe_dir, home_dir(), system_locale_dir())
}

/// Try to load a catalog for `code` from the search paths.
fn load_locale_file(code: &str) -> Option<Value> {
    let names = locale_filenames(code);
    for dir in locale_search_dirs() {
        for name in &names {
            if let Some(v) = try_load(&dir.join(name)) {
                return Some(v);
            }
        }
    }
    None
}

// The diagnostic for a locale file that could not be read, or None when it simply doesn't
// exist.
fn locale_read_diagnostic(path: &Path, error: &std::io::Error) -> Option<String> {
    (error.kind() != std::io::ErrorKind::NotFound).then(|| {
        format!(
            "freemkv: cannot read locale file {}: {}",
            path.display(),
            error
        )
    })
}

// A real catalog is tens of KB; refuse to buffer anything wildly larger.
const MAX_LOCALE_FILE_BYTES: u64 = 8 * 1024 * 1024; // 8 MiB

// Read `path` fully but refuse anything past `max_bytes` — a real catalog
// is tens of KB; larger is corrupt or hostile input. Returns an
// `InvalidData` error (never NotFound), reported like any unreadable file.
fn read_capped(path: &Path, max_bytes: u64) -> std::io::Result<String> {
    use std::io::Read;
    let mut buf = Vec::new();
    std::fs::File::open(path)?
        .take(max_bytes + 1)
        .read_to_end(&mut buf)?;
    if buf.len() as u64 > max_bytes {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!("locale file exceeds {max_bytes}-byte limit"),
        ));
    }
    String::from_utf8(buf).map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))
}

fn try_load(path: &Path) -> Option<Value> {
    let data = match read_capped(path, MAX_LOCALE_FILE_BYTES) {
        Ok(data) => data,
        Err(e) => {
            if let Some(msg) = locale_read_diagnostic(path, &e) {
                eprintln!("{msg}");
            }
            return None;
        }
    };
    // A missing file is fine (the loader tries the next search path), but a
    // file that exists yet fails to parse is almost certainly an operator
    // mistake — surface it instead of silently falling back to English.
    match serde_json::from_str(&data) {
        Ok(v) => Some(v),
        Err(e) => {
            eprintln!(
                "freemkv: ignoring invalid locale file {}: {}",
                path.display(),
                e
            );
            None
        }
    }
}

// Report a key that had to be served from English, once per key (returns whether it actually
// emitted).
fn report_missing_translation(path: &str) -> bool {
    static REPORTED: OnceLock<Mutex<BTreeSet<String>>> = OnceLock::new();
    let mut seen = REPORTED
        .get_or_init(|| Mutex::new(BTreeSet::new()))
        .lock()
        .unwrap_or_else(|e| e.into_inner());
    if seen.insert(path.to_string()) {
        eprintln!("freemkv: no translation for '{path}' in the active locale, using English");
        return true;
    }
    false
}

// Look up path, falling back to English, then to the path itself. A blank value counts as a
// miss.
fn lookup_or_english(strings: &Value, path: &str, active_is_english: bool) -> String {
    if let Some(s) = lookup_in(strings, path)
        && !s.trim().is_empty()
    {
        return s;
    }
    if !active_is_english
        && let Some(s) = lookup_in(english_catalog(), path)
        && !s.trim().is_empty()
    {
        report_missing_translation(path);
        return s;
    }
    path.to_string()
}

/// One catalog, no fallback. Returns `None` for a missing or non-string node so
/// the caller can decide what to do about it.
fn lookup_in(strings: &Value, path: &str) -> Option<String> {
    let mut node = strings;
    for part in path.split('.') {
        node = node.get(part)?;
    }
    node.as_str().map(|s| s.to_string())
}

#[cfg(test)]
#[path = "lib_tests.rs"]
mod tests;

#[cfg(test)]
#[path = "lib_fallback_tests.rs"]
mod fallback_tests;

#[cfg(test)]
#[path = "lib_error_code_coverage_tests.rs"]
mod error_code_coverage;
